/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package otelo.View;

import java.awt.Color;
import java.awt.Point;
import java.net.URL;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import otelo.logica.Colores;
import static otelo.logica.Colores.BLANCO;
import static otelo.logica.Colores.MORADO;
import otelo.logica.Juego;
import otelo.logica.Jugador;

/**
 
 * @author UTN
 */
public class PnOtello extends javax.swing.JPanel {

    
       private JButton [][] botones;
       private int [][] tablero; 
        Jugador juga1 = new Jugador("",MORADO,0);
        Jugador juga2 = new Jugador("",BLANCO,0);
        Jugador jugActual;
        Juego juego = new Juego();
        int[][] TableroInicial = juego.obtenerTableroInicial();
        URL imageURL1 = PnOtello.class.getResource("/otelo/View/images/magenta.png");
        URL imageURL2 = PnOtello.class.getResource("/otelo/View/images/negro.png");
        URL imageURL3 = PnOtello.class.getResource("/otelo/View/images/blanco.png");
        URL imageURL4 = PnOtello.class.getResource("/otelo/View/images/beige.png");
        ImageIcon icon1mora = new ImageIcon(imageURL1);
        ImageIcon icon2negro = new ImageIcon(imageURL2);
        ImageIcon iconBlanco = new ImageIcon(imageURL3);
        ImageIcon iconBeige = new ImageIcon(imageURL4);
        
    /**
     * Creates new form PnOtello
     */
    public PnOtello() {
        
        initComponents();
        NombresJugadores();
        Puntos();
        botones = new JButton [12][12];
        AsignarBtns();
        iniTurno();
        iniTablero();
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        btn0_0 = new javax.swing.JButton();
        btn0_1 = new javax.swing.JButton();
        btn0_2 = new javax.swing.JButton();
        btn0_3 = new javax.swing.JButton();
        btn0_4 = new javax.swing.JButton();
        btn0_5 = new javax.swing.JButton();
        btn0_6 = new javax.swing.JButton();
        btn0_7 = new javax.swing.JButton();
        btn0_8 = new javax.swing.JButton();
        btn0_9 = new javax.swing.JButton();
        btn0_10 = new javax.swing.JButton();
        btn0_11 = new javax.swing.JButton();
        btn1_0 = new javax.swing.JButton();
        btn1_1 = new javax.swing.JButton();
        btn1_2 = new javax.swing.JButton();
        btn1_3 = new javax.swing.JButton();
        btn1_4 = new javax.swing.JButton();
        btn1_5 = new javax.swing.JButton();
        btn1_6 = new javax.swing.JButton();
        btn1_7 = new javax.swing.JButton();
        btn1_8 = new javax.swing.JButton();
        btn1_9 = new javax.swing.JButton();
        btn1_10 = new javax.swing.JButton();
        btn1_11 = new javax.swing.JButton();
        btn2_0 = new javax.swing.JButton();
        btn2_1 = new javax.swing.JButton();
        btn2_2 = new javax.swing.JButton();
        btn2_3 = new javax.swing.JButton();
        btn2_4 = new javax.swing.JButton();
        btn2_5 = new javax.swing.JButton();
        btn2_6 = new javax.swing.JButton();
        btn2_7 = new javax.swing.JButton();
        btn2_8 = new javax.swing.JButton();
        btn2_9 = new javax.swing.JButton();
        btn2_10 = new javax.swing.JButton();
        btn2_11 = new javax.swing.JButton();
        btn3_0 = new javax.swing.JButton();
        btn3_1 = new javax.swing.JButton();
        btn3_2 = new javax.swing.JButton();
        btn3_3 = new javax.swing.JButton();
        btn3_4 = new javax.swing.JButton();
        btn3_5 = new javax.swing.JButton();
        btn3_6 = new javax.swing.JButton();
        btn3_7 = new javax.swing.JButton();
        btn3_8 = new javax.swing.JButton();
        btn3_9 = new javax.swing.JButton();
        btn3_10 = new javax.swing.JButton();
        btn3_11 = new javax.swing.JButton();
        btn4_0 = new javax.swing.JButton();
        btn4_1 = new javax.swing.JButton();
        btn4_2 = new javax.swing.JButton();
        btn4_3 = new javax.swing.JButton();
        btn4_4 = new javax.swing.JButton();
        btn4_5 = new javax.swing.JButton();
        btn4_6 = new javax.swing.JButton();
        btn4_7 = new javax.swing.JButton();
        btn4_8 = new javax.swing.JButton();
        btn4_9 = new javax.swing.JButton();
        btn4_10 = new javax.swing.JButton();
        btn4_11 = new javax.swing.JButton();
        btn5_0 = new javax.swing.JButton();
        btn5_1 = new javax.swing.JButton();
        btn5_2 = new javax.swing.JButton();
        btn5_3 = new javax.swing.JButton();
        btn5_4 = new javax.swing.JButton();
        btn5_5 = new javax.swing.JButton();
        btn5_6 = new javax.swing.JButton();
        btn5_7 = new javax.swing.JButton();
        btn5_8 = new javax.swing.JButton();
        btn5_9 = new javax.swing.JButton();
        btn5_10 = new javax.swing.JButton();
        btn5_11 = new javax.swing.JButton();
        btn6_0 = new javax.swing.JButton();
        btn6_1 = new javax.swing.JButton();
        btn6_2 = new javax.swing.JButton();
        btn6_3 = new javax.swing.JButton();
        btn6_4 = new javax.swing.JButton();
        btn6_5 = new javax.swing.JButton();
        btn6_6 = new javax.swing.JButton();
        btn6_7 = new javax.swing.JButton();
        btn6_8 = new javax.swing.JButton();
        btn6_9 = new javax.swing.JButton();
        btn6_10 = new javax.swing.JButton();
        btn6_11 = new javax.swing.JButton();
        btn7_0 = new javax.swing.JButton();
        btn7_1 = new javax.swing.JButton();
        btn7_2 = new javax.swing.JButton();
        btn7_3 = new javax.swing.JButton();
        btn7_4 = new javax.swing.JButton();
        btn7_5 = new javax.swing.JButton();
        btn7_6 = new javax.swing.JButton();
        btn7_7 = new javax.swing.JButton();
        btn7_8 = new javax.swing.JButton();
        btn7_9 = new javax.swing.JButton();
        btn7_10 = new javax.swing.JButton();
        btn7_11 = new javax.swing.JButton();
        btn8_0 = new javax.swing.JButton();
        btn8_1 = new javax.swing.JButton();
        btn8_2 = new javax.swing.JButton();
        btn8_3 = new javax.swing.JButton();
        btn8_4 = new javax.swing.JButton();
        btn8_5 = new javax.swing.JButton();
        btn8_6 = new javax.swing.JButton();
        btn8_7 = new javax.swing.JButton();
        btn8_8 = new javax.swing.JButton();
        btn8_9 = new javax.swing.JButton();
        btn8_10 = new javax.swing.JButton();
        btn8_11 = new javax.swing.JButton();
        btn9_0 = new javax.swing.JButton();
        btn9_1 = new javax.swing.JButton();
        btn9_2 = new javax.swing.JButton();
        btn9_3 = new javax.swing.JButton();
        btn9_4 = new javax.swing.JButton();
        btn9_5 = new javax.swing.JButton();
        btn9_6 = new javax.swing.JButton();
        btn9_7 = new javax.swing.JButton();
        btn9_8 = new javax.swing.JButton();
        btn9_9 = new javax.swing.JButton();
        btn9_10 = new javax.swing.JButton();
        btn9_11 = new javax.swing.JButton();
        btn10_0 = new javax.swing.JButton();
        btn10_1 = new javax.swing.JButton();
        btn10_2 = new javax.swing.JButton();
        btn10_3 = new javax.swing.JButton();
        btn10_4 = new javax.swing.JButton();
        btn10_5 = new javax.swing.JButton();
        btn10_6 = new javax.swing.JButton();
        btn10_7 = new javax.swing.JButton();
        btn10_8 = new javax.swing.JButton();
        btn10_9 = new javax.swing.JButton();
        btn10_10 = new javax.swing.JButton();
        btn10_11 = new javax.swing.JButton();
        btn11_0 = new javax.swing.JButton();
        btn11_1 = new javax.swing.JButton();
        btn11_2 = new javax.swing.JButton();
        btn11_3 = new javax.swing.JButton();
        btn11_4 = new javax.swing.JButton();
        btn11_5 = new javax.swing.JButton();
        btn11_6 = new javax.swing.JButton();
        btn11_7 = new javax.swing.JButton();
        btn11_8 = new javax.swing.JButton();
        btn11_9 = new javax.swing.JButton();
        btn11_10 = new javax.swing.JButton();
        btn11_11 = new javax.swing.JButton();
        lblJugador1 = new javax.swing.JLabel();
        lblJugador2 = new javax.swing.JLabel();
        lblFichas1 = new javax.swing.JLabel();
        lblFichas2 = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();
        btnReiniciar = new javax.swing.JButton();
        lbTurno = new javax.swing.JLabel();
        turno = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 255));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        setLayout(new java.awt.GridBagLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });
        jPanel1.setLayout(new java.awt.GridLayout(12, 12));

        btn0_0.setPreferredSize(new java.awt.Dimension(76, 40));
        jPanel1.add(btn0_0);

        btn0_1.setPreferredSize(new java.awt.Dimension(76, 40));
        jPanel1.add(btn0_1);

        btn0_2.setPreferredSize(new java.awt.Dimension(76, 40));
        jPanel1.add(btn0_2);

        btn0_3.setPreferredSize(new java.awt.Dimension(76, 40));
        jPanel1.add(btn0_3);

        btn0_4.setPreferredSize(new java.awt.Dimension(76, 40));
        jPanel1.add(btn0_4);

        btn0_5.setPreferredSize(new java.awt.Dimension(76, 40));
        jPanel1.add(btn0_5);

        btn0_6.setPreferredSize(new java.awt.Dimension(76, 40));
        jPanel1.add(btn0_6);

        btn0_7.setPreferredSize(new java.awt.Dimension(76, 40));
        jPanel1.add(btn0_7);

        btn0_8.setPreferredSize(new java.awt.Dimension(76, 40));
        jPanel1.add(btn0_8);

        btn0_9.setPreferredSize(new java.awt.Dimension(76, 40));
        jPanel1.add(btn0_9);

        btn0_10.setPreferredSize(new java.awt.Dimension(76, 40));
        jPanel1.add(btn0_10);

        btn0_11.setPreferredSize(new java.awt.Dimension(76, 40));
        jPanel1.add(btn0_11);

        btn1_0.setPreferredSize(new java.awt.Dimension(76, 40));
        jPanel1.add(btn1_0);

        btn1_1.setPreferredSize(new java.awt.Dimension(76, 40));
        jPanel1.add(btn1_1);

        btn1_2.setPreferredSize(new java.awt.Dimension(76, 40));
        jPanel1.add(btn1_2);

        btn1_3.setPreferredSize(new java.awt.Dimension(76, 40));
        jPanel1.add(btn1_3);

        btn1_4.setPreferredSize(new java.awt.Dimension(76, 40));
        jPanel1.add(btn1_4);

        btn1_5.setPreferredSize(new java.awt.Dimension(76, 40));
        jPanel1.add(btn1_5);

        btn1_6.setPreferredSize(new java.awt.Dimension(76, 40));
        jPanel1.add(btn1_6);

        btn1_7.setPreferredSize(new java.awt.Dimension(76, 40));
        jPanel1.add(btn1_7);

        btn1_8.setPreferredSize(new java.awt.Dimension(76, 40));
        jPanel1.add(btn1_8);

        btn1_9.setPreferredSize(new java.awt.Dimension(76, 40));
        jPanel1.add(btn1_9);

        btn1_10.setPreferredSize(new java.awt.Dimension(76, 40));
        jPanel1.add(btn1_10);

        btn1_11.setPreferredSize(new java.awt.Dimension(76, 40));
        jPanel1.add(btn1_11);

        btn2_0.setPreferredSize(new java.awt.Dimension(76, 40));
        jPanel1.add(btn2_0);

        btn2_1.setPreferredSize(new java.awt.Dimension(76, 40));
        jPanel1.add(btn2_1);

        btn2_2.setPreferredSize(new java.awt.Dimension(76, 40));
        jPanel1.add(btn2_2);

        btn2_3.setPreferredSize(new java.awt.Dimension(76, 40));
        jPanel1.add(btn2_3);

        btn2_4.setPreferredSize(new java.awt.Dimension(76, 40));
        jPanel1.add(btn2_4);

        btn2_5.setPreferredSize(new java.awt.Dimension(76, 40));
        jPanel1.add(btn2_5);

        btn2_6.setPreferredSize(new java.awt.Dimension(76, 40));
        jPanel1.add(btn2_6);

        btn2_7.setPreferredSize(new java.awt.Dimension(76, 40));
        jPanel1.add(btn2_7);

        btn2_8.setPreferredSize(new java.awt.Dimension(76, 40));
        jPanel1.add(btn2_8);

        btn2_9.setPreferredSize(new java.awt.Dimension(76, 40));
        jPanel1.add(btn2_9);

        btn2_10.setPreferredSize(new java.awt.Dimension(76, 40));
        jPanel1.add(btn2_10);

        btn2_11.setPreferredSize(new java.awt.Dimension(76, 40));
        jPanel1.add(btn2_11);

        btn3_0.setPreferredSize(new java.awt.Dimension(76, 40));
        jPanel1.add(btn3_0);

        btn3_1.setPreferredSize(new java.awt.Dimension(76, 40));
        jPanel1.add(btn3_1);

        btn3_2.setPreferredSize(new java.awt.Dimension(76, 40));
        jPanel1.add(btn3_2);

        btn3_3.setPreferredSize(new java.awt.Dimension(76, 40));
        jPanel1.add(btn3_3);

        btn3_4.setPreferredSize(new java.awt.Dimension(76, 40));
        jPanel1.add(btn3_4);

        btn3_5.setPreferredSize(new java.awt.Dimension(76, 40));
        jPanel1.add(btn3_5);

        btn3_6.setPreferredSize(new java.awt.Dimension(76, 40));
        jPanel1.add(btn3_6);

        btn3_7.setPreferredSize(new java.awt.Dimension(76, 40));
        jPanel1.add(btn3_7);

        btn3_8.setPreferredSize(new java.awt.Dimension(76, 40));
        jPanel1.add(btn3_8);

        btn3_9.setPreferredSize(new java.awt.Dimension(76, 40));
        jPanel1.add(btn3_9);

        btn3_10.setPreferredSize(new java.awt.Dimension(76, 40));
        jPanel1.add(btn3_10);

        btn3_11.setPreferredSize(new java.awt.Dimension(76, 40));
        jPanel1.add(btn3_11);

        btn4_0.setPreferredSize(new java.awt.Dimension(76, 40));
        jPanel1.add(btn4_0);

        btn4_1.setPreferredSize(new java.awt.Dimension(76, 40));
        jPanel1.add(btn4_1);

        btn4_2.setPreferredSize(new java.awt.Dimension(76, 40));
        jPanel1.add(btn4_2);

        btn4_3.setPreferredSize(new java.awt.Dimension(76, 40));
        jPanel1.add(btn4_3);

        btn4_4.setPreferredSize(new java.awt.Dimension(76, 40));
        jPanel1.add(btn4_4);

        btn4_5.setPreferredSize(new java.awt.Dimension(76, 40));
        jPanel1.add(btn4_5);

        btn4_6.setPreferredSize(new java.awt.Dimension(76, 40));
        jPanel1.add(btn4_6);

        btn4_7.setPreferredSize(new java.awt.Dimension(76, 40));
        jPanel1.add(btn4_7);

        btn4_8.setPreferredSize(new java.awt.Dimension(76, 40));
        jPanel1.add(btn4_8);

        btn4_9.setPreferredSize(new java.awt.Dimension(76, 40));
        jPanel1.add(btn4_9);

        btn4_10.setPreferredSize(new java.awt.Dimension(76, 40));
        jPanel1.add(btn4_10);

        btn4_11.setPreferredSize(new java.awt.Dimension(76, 40));
        jPanel1.add(btn4_11);

        btn5_0.setPreferredSize(new java.awt.Dimension(76, 40));
        jPanel1.add(btn5_0);

        btn5_1.setPreferredSize(new java.awt.Dimension(76, 40));
        jPanel1.add(btn5_1);

        btn5_2.setPreferredSize(new java.awt.Dimension(76, 40));
        jPanel1.add(btn5_2);

        btn5_3.setPreferredSize(new java.awt.Dimension(76, 40));
        jPanel1.add(btn5_3);

        btn5_4.setPreferredSize(new java.awt.Dimension(76, 40));
        jPanel1.add(btn5_4);

        btn5_5.setPreferredSize(new java.awt.Dimension(76, 40));
        jPanel1.add(btn5_5);

        btn5_6.setPreferredSize(new java.awt.Dimension(76, 40));
        jPanel1.add(btn5_6);

        btn5_7.setPreferredSize(new java.awt.Dimension(76, 40));
        jPanel1.add(btn5_7);

        btn5_8.setPreferredSize(new java.awt.Dimension(76, 40));
        jPanel1.add(btn5_8);

        btn5_9.setPreferredSize(new java.awt.Dimension(76, 40));
        jPanel1.add(btn5_9);

        btn5_10.setPreferredSize(new java.awt.Dimension(76, 40));
        jPanel1.add(btn5_10);

        btn5_11.setPreferredSize(new java.awt.Dimension(76, 40));
        jPanel1.add(btn5_11);

        btn6_0.setPreferredSize(new java.awt.Dimension(76, 40));
        jPanel1.add(btn6_0);

        btn6_1.setPreferredSize(new java.awt.Dimension(76, 40));
        jPanel1.add(btn6_1);

        btn6_2.setPreferredSize(new java.awt.Dimension(76, 40));
        jPanel1.add(btn6_2);

        btn6_3.setPreferredSize(new java.awt.Dimension(76, 40));
        jPanel1.add(btn6_3);

        btn6_4.setPreferredSize(new java.awt.Dimension(76, 40));
        jPanel1.add(btn6_4);

        btn6_5.setPreferredSize(new java.awt.Dimension(76, 40));
        jPanel1.add(btn6_5);

        btn6_6.setPreferredSize(new java.awt.Dimension(76, 40));
        jPanel1.add(btn6_6);

        btn6_7.setPreferredSize(new java.awt.Dimension(76, 40));
        jPanel1.add(btn6_7);

        btn6_8.setPreferredSize(new java.awt.Dimension(76, 40));
        jPanel1.add(btn6_8);

        btn6_9.setPreferredSize(new java.awt.Dimension(76, 40));
        jPanel1.add(btn6_9);

        btn6_10.setPreferredSize(new java.awt.Dimension(76, 40));
        jPanel1.add(btn6_10);

        btn6_11.setPreferredSize(new java.awt.Dimension(76, 40));
        jPanel1.add(btn6_11);

        btn7_0.setPreferredSize(new java.awt.Dimension(76, 40));
        jPanel1.add(btn7_0);

        btn7_1.setPreferredSize(new java.awt.Dimension(76, 40));
        jPanel1.add(btn7_1);

        btn7_2.setPreferredSize(new java.awt.Dimension(76, 40));
        jPanel1.add(btn7_2);

        btn7_3.setPreferredSize(new java.awt.Dimension(76, 40));
        jPanel1.add(btn7_3);

        btn7_4.setPreferredSize(new java.awt.Dimension(76, 40));
        jPanel1.add(btn7_4);

        btn7_5.setPreferredSize(new java.awt.Dimension(76, 40));
        jPanel1.add(btn7_5);

        btn7_6.setPreferredSize(new java.awt.Dimension(76, 40));
        jPanel1.add(btn7_6);

        btn7_7.setPreferredSize(new java.awt.Dimension(76, 40));
        jPanel1.add(btn7_7);

        btn7_8.setPreferredSize(new java.awt.Dimension(76, 40));
        jPanel1.add(btn7_8);

        btn7_9.setPreferredSize(new java.awt.Dimension(76, 40));
        jPanel1.add(btn7_9);

        btn7_10.setPreferredSize(new java.awt.Dimension(76, 40));
        jPanel1.add(btn7_10);

        btn7_11.setPreferredSize(new java.awt.Dimension(76, 40));
        jPanel1.add(btn7_11);

        btn8_0.setPreferredSize(new java.awt.Dimension(76, 40));
        jPanel1.add(btn8_0);

        btn8_1.setPreferredSize(new java.awt.Dimension(76, 40));
        jPanel1.add(btn8_1);

        btn8_2.setPreferredSize(new java.awt.Dimension(76, 40));
        jPanel1.add(btn8_2);

        btn8_3.setPreferredSize(new java.awt.Dimension(76, 40));
        jPanel1.add(btn8_3);

        btn8_4.setPreferredSize(new java.awt.Dimension(76, 40));
        jPanel1.add(btn8_4);

        btn8_5.setPreferredSize(new java.awt.Dimension(76, 40));
        jPanel1.add(btn8_5);

        btn8_6.setPreferredSize(new java.awt.Dimension(76, 40));
        jPanel1.add(btn8_6);

        btn8_7.setPreferredSize(new java.awt.Dimension(76, 40));
        jPanel1.add(btn8_7);

        btn8_8.setPreferredSize(new java.awt.Dimension(76, 40));
        jPanel1.add(btn8_8);

        btn8_9.setPreferredSize(new java.awt.Dimension(76, 40));
        jPanel1.add(btn8_9);

        btn8_10.setPreferredSize(new java.awt.Dimension(76, 40));
        jPanel1.add(btn8_10);

        btn8_11.setPreferredSize(new java.awt.Dimension(76, 40));
        jPanel1.add(btn8_11);

        btn9_0.setPreferredSize(new java.awt.Dimension(76, 40));
        jPanel1.add(btn9_0);

        btn9_1.setPreferredSize(new java.awt.Dimension(76, 40));
        jPanel1.add(btn9_1);

        btn9_2.setPreferredSize(new java.awt.Dimension(76, 40));
        jPanel1.add(btn9_2);

        btn9_3.setPreferredSize(new java.awt.Dimension(76, 40));
        jPanel1.add(btn9_3);

        btn9_4.setPreferredSize(new java.awt.Dimension(76, 40));
        jPanel1.add(btn9_4);
        jPanel1.add(btn9_5);

        btn9_6.setPreferredSize(new java.awt.Dimension(76, 40));
        jPanel1.add(btn9_6);

        btn9_7.setPreferredSize(new java.awt.Dimension(76, 40));
        jPanel1.add(btn9_7);

        btn9_8.setPreferredSize(new java.awt.Dimension(76, 40));
        jPanel1.add(btn9_8);

        btn9_9.setPreferredSize(new java.awt.Dimension(76, 40));
        jPanel1.add(btn9_9);

        btn9_10.setPreferredSize(new java.awt.Dimension(76, 40));
        jPanel1.add(btn9_10);

        btn9_11.setPreferredSize(new java.awt.Dimension(76, 40));
        jPanel1.add(btn9_11);

        btn10_0.setPreferredSize(new java.awt.Dimension(76, 40));
        jPanel1.add(btn10_0);

        btn10_1.setPreferredSize(new java.awt.Dimension(76, 40));
        jPanel1.add(btn10_1);

        btn10_2.setPreferredSize(new java.awt.Dimension(76, 40));
        jPanel1.add(btn10_2);

        btn10_3.setPreferredSize(new java.awt.Dimension(76, 40));
        jPanel1.add(btn10_3);

        btn10_4.setPreferredSize(new java.awt.Dimension(76, 40));
        jPanel1.add(btn10_4);

        btn10_5.setPreferredSize(new java.awt.Dimension(76, 40));
        jPanel1.add(btn10_5);

        btn10_6.setPreferredSize(new java.awt.Dimension(76, 40));
        jPanel1.add(btn10_6);

        btn10_7.setPreferredSize(new java.awt.Dimension(76, 40));
        jPanel1.add(btn10_7);

        btn10_8.setPreferredSize(new java.awt.Dimension(76, 40));
        jPanel1.add(btn10_8);

        btn10_9.setPreferredSize(new java.awt.Dimension(76, 40));
        jPanel1.add(btn10_9);

        btn10_10.setPreferredSize(new java.awt.Dimension(76, 40));
        jPanel1.add(btn10_10);

        btn10_11.setPreferredSize(new java.awt.Dimension(76, 40));
        jPanel1.add(btn10_11);

        btn11_0.setPreferredSize(new java.awt.Dimension(76, 40));
        jPanel1.add(btn11_0);

        btn11_1.setPreferredSize(new java.awt.Dimension(76, 40));
        jPanel1.add(btn11_1);

        btn11_2.setPreferredSize(new java.awt.Dimension(76, 40));
        jPanel1.add(btn11_2);

        btn11_3.setPreferredSize(new java.awt.Dimension(76, 40));
        jPanel1.add(btn11_3);

        btn11_4.setPreferredSize(new java.awt.Dimension(76, 40));
        jPanel1.add(btn11_4);

        btn11_5.setPreferredSize(new java.awt.Dimension(76, 40));
        jPanel1.add(btn11_5);

        btn11_6.setPreferredSize(new java.awt.Dimension(76, 40));
        jPanel1.add(btn11_6);

        btn11_7.setPreferredSize(new java.awt.Dimension(76, 40));
        jPanel1.add(btn11_7);

        btn11_8.setPreferredSize(new java.awt.Dimension(76, 40));
        jPanel1.add(btn11_8);

        btn11_9.setPreferredSize(new java.awt.Dimension(76, 40));
        jPanel1.add(btn11_9);

        btn11_10.setPreferredSize(new java.awt.Dimension(76, 40));
        jPanel1.add(btn11_10);

        btn11_11.setPreferredSize(new java.awt.Dimension(76, 40));
        jPanel1.add(btn11_11);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.ipadx = 3;
        gridBagConstraints.insets = new java.awt.Insets(18, 67, 6, 0);
        add(jPanel1, gridBagConstraints);

        lblJugador1.setFont(new java.awt.Font("Serif", 3, 28)); // NOI18N
        lblJugador1.setText("Jugador 1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 73, 0, 10);
        add(lblJugador1, gridBagConstraints);

        lblJugador2.setFont(new java.awt.Font("Serif", 3, 28)); // NOI18N
        lblJugador2.setText("Jugador 2");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 150, 0, 0);
        add(lblJugador2, gridBagConstraints);

        lblFichas1.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        lblFichas1.setText("#fichas");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(8, 4, 0, 1);
        add(lblFichas1, gridBagConstraints);

        lblFichas2.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        lblFichas2.setText("#fichas");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(9, 14, 0, 0);
        add(lblFichas2, gridBagConstraints);

        btnSalir.setText("SALIR");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 17, 0, 17);
        add(btnSalir, gridBagConstraints);

        btnReiniciar.setText("REINICIAR");
        btnReiniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReiniciarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 11, 0, 10);
        add(btnReiniciar, gridBagConstraints);

        lbTurno.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        lbTurno.setText("Turno de:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 450, 0);
        add(lbTurno, gridBagConstraints);

        turno.setFont(new java.awt.Font("Serif", 3, 28)); // NOI18N
        turno.setText("turno");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 350, 0);
        add(turno, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void btnReiniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReiniciarActionPerformed
        reiniciarJuego();
        
    }//GEN-LAST:event_btnReiniciarActionPerformed

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
       
        
    }//GEN-LAST:event_formMouseClicked

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
        int a= evt.getX();
        int B= evt.getY();
        int fila =-1;
        int columna =-1;
        for (int i = 0; i < 16; i++) {
            for (int j = 0; j < 16; j++) {
                if (this.botones[i][j].getBounds().contains(a,B)) {
                    fila =i;columna=j;
                    break;
                }
            }
        }
        if (fila != -1 && columna != -1 && juego.movimientoValido(fila, columna) && jugActual==juga1) {
            juego.realizarMovimiento(fila, columna, MORADO);
            ArrayList<Point> fichasAtrapa = juego.calcularFichasAtrapadas(fila, columna, MORADO);

            for (Point punto : fichasAtrapa) {
                int x=(int)punto.getX();
                int y=(int)punto.getY();
                juego.realizarMovimiento(x, y, MORADO);
                CambiarIcon(jugActual, x, y);
                jugActual.agregarFicha();
            }
            jugActual=(jugActual==juga1)?juga2 :juga1;

        }else if(fila != -1 && columna != -1 && juego.movimientoValido(fila, columna) && jugActual==juga2) {
            juego.realizarMovimiento(fila, columna, MORADO);
            ArrayList<Point> fichasAtrapa = juego.calcularFichasAtrapadas(fila, columna, MORADO);

            for (Point punto : fichasAtrapa) {
                int x=(int)punto.getX();
                int y=(int)punto.getY();
                juego.realizarMovimiento(x, y, MORADO);
                CambiarIcon(jugActual, x, y);
                jugActual.agregarFicha();
            }
            jugActual=(jugActual==juga2)?juga1 :juga2;

        }
        turno.setText(jugActual.getNombre());

        lblFichas1.setText(Integer.toString(juga1.Puntuacion()));
        lblFichas2.setText(Integer.toString(juga2.Puntuacion()));
    }//GEN-LAST:event_jPanel1MouseClicked

    public void CambiarIcon(Jugador jugActual, int x, int y){
        if (jugActual == juga1) {
            this.botones[x][y].setIcon(icon1mora);
        }
        if (jugActual == juga2) {
            this.botones[x][y].setIcon(icon2negro);
        }
    }
    public void NombresJugadores(){
        String nombr1 = JOptionPane.showInputDialog("Introduzca nombre jugador 1");
        juga1.setNombre(nombr1);
        lblJugador1.setText(juga1.getNombre());
        String nombre2 = JOptionPane.showInputDialog("Introduzca nombre jugador 2");
        juga2.setNombre(nombre2);
        lblJugador2.setText(juga2.getNombre());
    }
    
    public void Puntos(){
        lblFichas1.setText(Integer.toString(juga1.Puntuacion()));
        lblFichas2.setText(Integer.toString(juga2.Puntuacion()));
        
    }
    
    public void iniTurno(){
        
        jugActual = juga1;
        turno.setText(jugActual.getNombre());
    }
    
    
    public void iniTablero(){
        
           for (int i = 0; i < 12; i++) {
                  for (int j = 0; j < 12; j++) {
                      if (i==5 || i ==6 && j==5 || j==6) {
                          if (TableroInicial[i][j] == 1) {
                                this.botones[i][j].setEnabled(true);
                                this.botones[i][j].setIcon(icon1mora);
                                continue;
                           }else if (TableroInicial[i][j]== 2) {
                                this.botones[i][j].setEnabled(true);
                                this.botones[i][j].setIcon(icon2negro);
                                continue;
                        }
                      }
                            this.botones[i][j].setIcon(iconBlanco);
                            this.botones[i][j].setOpaque(true);
                            this.botones[i][j].setEnabled(true);
                                        
               } 
               }
               
               
        
    }
    private void reiniciarJuego(){
        int opcion  = JOptionPane.showConfirmDialog(this,"Desea reiniciar el juego?", "Reiniciar Juego",JOptionPane.YES_NO_OPTION);
        if (opcion==JOptionPane.YES_NO_OPTION) {
            juego.reiniciarJuego();
            juga1.setCantFichas(2);
            juga2.setCantFichas(2);
            lblFichas1.setText("2");
            lblFichas2.setText("2");
            jugActual = juga1;
            turno.setText(jugActual.getNombre());
        
        // Actualizar la interfaz gráfica
            iniTablero();
        }
    }
    public void reiniciarTablero() {
    juego.inicializarTablero();
    iniTablero();
    }
//    public void mostrarMovimientosValidos() { 
//
//    for (int i = 0; i < 12; i++) {
//        for (int j = 0; j < 12; j++) {
//            if (juego.movimientoValido(i, j)) {
//                this.botones[i][j].setBackground(Color.GREEN);
//            } else {
//                // Establece otro color de fondo para las celdas no válidas
//                this.botones[i][j].setBackground(Color.BLUE);
//            }
//        }
//    }
//}

    public void AsignarBtns(){
        this.botones [0][0] = btn0_0;
        this.botones [0][1] = btn0_1;
        this.botones [0][2] = btn0_2;
        this.botones [0][3] = btn0_3;
        this.botones [0][4] = btn0_4;
        this.botones [0][5] = btn0_5;
        this.botones [0][6] = btn0_6;
        this.botones [0][7] = btn0_7;
        this.botones [0][8] = btn0_8;
        this.botones [0][9] = btn0_9;
        this.botones [0][10] = btn0_10;
        this.botones [0][11] = btn0_11;
        this.botones [1][0] = btn1_0;
        this.botones [1][1] = btn1_1;
        this.botones [1][2] = btn1_2;
        this.botones [1][3] = btn1_3;
        this.botones [1][4] = btn1_4;
        this.botones [1][5] = btn1_5;
        this.botones [1][6] = btn1_6;
        this.botones [1][7] = btn1_7;
        this.botones [1][8] = btn1_8;
        this.botones [1][9] = btn1_9;
        this.botones [1][10] = btn1_10;
        this.botones [1][11] = btn1_11;
        this.botones [2][0] = btn2_0;
        this.botones [2][1] = btn2_1;
        this.botones [2][2] = btn2_2;
        this.botones [2][3] = btn2_3;
        this.botones [2][4] = btn2_4;
        this.botones [2][5] = btn2_5;
        this.botones [2][6] = btn2_6;
        this.botones [2][7] = btn2_7;
        this.botones [2][8] = btn2_8;
        this.botones [2][9] = btn2_9;
        this.botones [2][10] = btn2_10;
        this.botones [2][11] = btn2_11;
        this.botones [3][0] = btn3_0;
        this.botones [3][1] = btn3_1;
        this.botones [3][2] = btn3_2;
        this.botones [3][3] = btn3_3;
        this.botones [3][4] = btn3_4;
        this.botones [3][5] = btn3_5;
        this.botones [3][6] = btn3_6;
        this.botones [3][7] = btn3_7;
        this.botones [3][8] = btn3_8;
        this.botones [3][9] = btn3_9;
        this.botones [3][10] = btn3_10;
        this.botones [3][11] = btn3_11;
        this.botones [4][0] = btn4_0;
        this.botones [4][1] = btn4_1;
        this.botones [4][2] = btn4_2;
        this.botones [4][3] = btn4_3;
        this.botones [4][4] = btn4_4;
        this.botones [4][5] = btn4_5;
        this.botones [4][6] = btn4_6;
        this.botones [4][7] = btn4_7;
        this.botones [4][8] = btn4_8;
        this.botones [4][9] = btn4_9;
        this.botones [4][10] = btn4_10;
        this.botones [4][11] = btn4_11;
        this.botones [5][0] = btn5_0;
        this.botones [5][1] = btn5_1;
        this.botones [5][2] = btn5_2;
        this.botones [5][3] = btn5_3;
        this.botones [5][4] = btn5_4;
        this.botones [5][5] = btn5_5;
        this.botones [5][6] = btn5_6;
        this.botones [5][7] = btn5_7;
        this.botones [5][8] = btn5_8;
        this.botones [5][9] = btn5_9;
        this.botones [5][10] = btn5_10;
        this.botones [5][11] = btn5_11;
        this.botones [6][0] = btn6_0;
        this.botones [6][1] = btn6_1;
        this.botones [6][2] = btn6_2;
        this.botones [6][3] = btn6_3;
        this.botones [6][4] = btn6_4;
        this.botones [6][5] = btn6_5;
        this.botones [6][6] = btn6_6;
        this.botones [6][7] = btn6_7;
        this.botones [6][8] = btn6_8;
        this.botones [6][9] = btn6_9;
        this.botones [6][10] = btn6_10;
        this.botones [6][11] = btn6_11;
        this.botones [7][0] = btn7_0;
        this.botones [7][1] = btn7_1;
        this.botones [7][2] = btn7_2;
        this.botones [7][3] = btn7_3;
        this.botones [7][4] = btn7_4;
        this.botones [7][5] = btn7_5;
        this.botones [7][6] = btn7_6;
        this.botones [7][7] = btn7_7;
        this.botones [7][8] = btn7_8;
        this.botones [7][9] = btn7_9;
        this.botones [7][10] = btn7_10;
        this.botones [7][11] = btn7_11;
        this.botones [8][0] = btn8_0;
        this.botones [8][1] = btn8_1;
        this.botones [8][2] = btn8_2;
        this.botones [8][3] = btn8_3;
        this.botones [8][4] = btn8_4;
        this.botones [8][5] = btn8_5;
        this.botones [8][6] = btn8_6;
        this.botones [8][7] = btn8_7;
        this.botones [8][8] = btn8_8;
        this.botones [8][9] = btn8_9;
        this.botones [8][10] = btn8_10;
        this.botones [8][11] = btn8_11;
        this.botones [9][0] = btn9_0;
        this.botones [9][1] = btn9_1;
        this.botones [9][2] = btn9_2;
        this.botones [9][3] = btn9_3;
        this.botones [9][4] = btn9_4;
        this.botones [9][5] = btn9_5;
        this.botones [9][6] = btn9_6;
        this.botones [9][7] = btn9_7;
        this.botones [9][8] = btn9_8;
        this.botones [9][9] = btn9_9;
        this.botones [9][10] = btn9_10;
        this.botones [9][11] = btn9_11;
        this.botones [10][0] = btn10_0;
        this.botones [10][1] = btn10_1;
        this.botones [10][2] = btn10_2;
        this.botones [10][3] = btn10_3;
        this.botones [10][4] = btn10_4;
        this.botones [10][5] = btn10_5;
        this.botones [10][6] = btn10_6;
        this.botones [10][7] = btn10_7;
        this.botones [10][8] = btn10_8;
        this.botones [10][9] = btn10_9;
        this.botones [10][10] = btn10_10;
        this.botones [10][11] = btn10_11;
        this.botones [11][0] = btn11_0;
        this.botones [11][1] = btn11_1;
        this.botones [11][2] = btn11_2;
        this.botones [11][3] = btn11_3;
        this.botones [11][4] = btn11_4;
        this.botones [11][5] = btn11_5;
        this.botones [11][6] = btn11_6;
        this.botones [11][7] = btn11_7;
        this.botones [11][8] = btn11_8;
        this.botones [11][9] = btn11_9;
        this.botones [11][10] = btn11_10;
        this.botones [11][11] = btn11_11;
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn0_0;
    private javax.swing.JButton btn0_1;
    private javax.swing.JButton btn0_10;
    private javax.swing.JButton btn0_11;
    private javax.swing.JButton btn0_2;
    private javax.swing.JButton btn0_3;
    private javax.swing.JButton btn0_4;
    private javax.swing.JButton btn0_5;
    private javax.swing.JButton btn0_6;
    private javax.swing.JButton btn0_7;
    private javax.swing.JButton btn0_8;
    private javax.swing.JButton btn0_9;
    private javax.swing.JButton btn10_0;
    private javax.swing.JButton btn10_1;
    private javax.swing.JButton btn10_10;
    private javax.swing.JButton btn10_11;
    private javax.swing.JButton btn10_2;
    private javax.swing.JButton btn10_3;
    private javax.swing.JButton btn10_4;
    private javax.swing.JButton btn10_5;
    private javax.swing.JButton btn10_6;
    private javax.swing.JButton btn10_7;
    private javax.swing.JButton btn10_8;
    private javax.swing.JButton btn10_9;
    private javax.swing.JButton btn11_0;
    private javax.swing.JButton btn11_1;
    private javax.swing.JButton btn11_10;
    private javax.swing.JButton btn11_11;
    private javax.swing.JButton btn11_2;
    private javax.swing.JButton btn11_3;
    private javax.swing.JButton btn11_4;
    private javax.swing.JButton btn11_5;
    private javax.swing.JButton btn11_6;
    private javax.swing.JButton btn11_7;
    private javax.swing.JButton btn11_8;
    private javax.swing.JButton btn11_9;
    private javax.swing.JButton btn1_0;
    private javax.swing.JButton btn1_1;
    private javax.swing.JButton btn1_10;
    private javax.swing.JButton btn1_11;
    private javax.swing.JButton btn1_2;
    private javax.swing.JButton btn1_3;
    private javax.swing.JButton btn1_4;
    private javax.swing.JButton btn1_5;
    private javax.swing.JButton btn1_6;
    private javax.swing.JButton btn1_7;
    private javax.swing.JButton btn1_8;
    private javax.swing.JButton btn1_9;
    private javax.swing.JButton btn2_0;
    private javax.swing.JButton btn2_1;
    private javax.swing.JButton btn2_10;
    private javax.swing.JButton btn2_11;
    private javax.swing.JButton btn2_2;
    private javax.swing.JButton btn2_3;
    private javax.swing.JButton btn2_4;
    private javax.swing.JButton btn2_5;
    private javax.swing.JButton btn2_6;
    private javax.swing.JButton btn2_7;
    private javax.swing.JButton btn2_8;
    private javax.swing.JButton btn2_9;
    private javax.swing.JButton btn3_0;
    private javax.swing.JButton btn3_1;
    private javax.swing.JButton btn3_10;
    private javax.swing.JButton btn3_11;
    private javax.swing.JButton btn3_2;
    private javax.swing.JButton btn3_3;
    private javax.swing.JButton btn3_4;
    private javax.swing.JButton btn3_5;
    private javax.swing.JButton btn3_6;
    private javax.swing.JButton btn3_7;
    private javax.swing.JButton btn3_8;
    private javax.swing.JButton btn3_9;
    private javax.swing.JButton btn4_0;
    private javax.swing.JButton btn4_1;
    private javax.swing.JButton btn4_10;
    private javax.swing.JButton btn4_11;
    private javax.swing.JButton btn4_2;
    private javax.swing.JButton btn4_3;
    private javax.swing.JButton btn4_4;
    private javax.swing.JButton btn4_5;
    private javax.swing.JButton btn4_6;
    private javax.swing.JButton btn4_7;
    private javax.swing.JButton btn4_8;
    private javax.swing.JButton btn4_9;
    private javax.swing.JButton btn5_0;
    private javax.swing.JButton btn5_1;
    private javax.swing.JButton btn5_10;
    private javax.swing.JButton btn5_11;
    private javax.swing.JButton btn5_2;
    private javax.swing.JButton btn5_3;
    private javax.swing.JButton btn5_4;
    private javax.swing.JButton btn5_5;
    private javax.swing.JButton btn5_6;
    private javax.swing.JButton btn5_7;
    private javax.swing.JButton btn5_8;
    private javax.swing.JButton btn5_9;
    private javax.swing.JButton btn6_0;
    private javax.swing.JButton btn6_1;
    private javax.swing.JButton btn6_10;
    private javax.swing.JButton btn6_11;
    private javax.swing.JButton btn6_2;
    private javax.swing.JButton btn6_3;
    private javax.swing.JButton btn6_4;
    private javax.swing.JButton btn6_5;
    private javax.swing.JButton btn6_6;
    private javax.swing.JButton btn6_7;
    private javax.swing.JButton btn6_8;
    private javax.swing.JButton btn6_9;
    private javax.swing.JButton btn7_0;
    private javax.swing.JButton btn7_1;
    private javax.swing.JButton btn7_10;
    private javax.swing.JButton btn7_11;
    private javax.swing.JButton btn7_2;
    private javax.swing.JButton btn7_3;
    private javax.swing.JButton btn7_4;
    private javax.swing.JButton btn7_5;
    private javax.swing.JButton btn7_6;
    private javax.swing.JButton btn7_7;
    private javax.swing.JButton btn7_8;
    private javax.swing.JButton btn7_9;
    private javax.swing.JButton btn8_0;
    private javax.swing.JButton btn8_1;
    private javax.swing.JButton btn8_10;
    private javax.swing.JButton btn8_11;
    private javax.swing.JButton btn8_2;
    private javax.swing.JButton btn8_3;
    private javax.swing.JButton btn8_4;
    private javax.swing.JButton btn8_5;
    private javax.swing.JButton btn8_6;
    private javax.swing.JButton btn8_7;
    private javax.swing.JButton btn8_8;
    private javax.swing.JButton btn8_9;
    private javax.swing.JButton btn9_0;
    private javax.swing.JButton btn9_1;
    private javax.swing.JButton btn9_10;
    private javax.swing.JButton btn9_11;
    private javax.swing.JButton btn9_2;
    private javax.swing.JButton btn9_3;
    private javax.swing.JButton btn9_4;
    private javax.swing.JButton btn9_5;
    private javax.swing.JButton btn9_6;
    private javax.swing.JButton btn9_7;
    private javax.swing.JButton btn9_8;
    private javax.swing.JButton btn9_9;
    private javax.swing.JButton btnReiniciar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbTurno;
    private javax.swing.JLabel lblFichas1;
    private javax.swing.JLabel lblFichas2;
    private javax.swing.JLabel lblJugador1;
    private javax.swing.JLabel lblJugador2;
    private javax.swing.JLabel turno;
    // End of variables declaration//GEN-END:variables
}
